import dicc_pin as pin

PIN_SIPO_OUT_Q0     = pin.DICC_PIN_16_15
PIN_SIPO_OUT_Q1     = pin.DICC_PIN_16_1
PIN_SIPO_OUT_Q2     = pin.DICC_PIN_16_2
PIN_SIPO_OUT_Q3     = pin.DICC_PIN_16_3
PIN_SIPO_OUT_Q4     = pin.DICC_PIN_16_4
PIN_SIPO_OUT_Q5     = pin.DICC_PIN_16_5
PIN_SIPO_OUT_Q6     = pin.DICC_PIN_16_6
PIN_SIPO_OUT_Q7     = pin.DICC_PIN_16_7
PIN_SIPO_OUT_Q7_NOT = pin.DICC_PIN_16_9

PIN_SIPO_IN_DATA    = pin.DICC_PIN_16_14
PIN_SIPO_IN_LATCH   = pin.DICC_PIN_16_12
PIN_SIPO_IN_CLOCK   = pin.DICC_PIN_16_11

PIN_SIPO_IN_OP_ENBL = pin.DICC_PIN_16_13
PIN_SIPO_IN_RESET   = pin.DICC_PIN_16_10
