name: Version File Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-version-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch at least two commits to allow comparison with previous commit

      - name: Check if config.json has been updated
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "firmware/config.json"; then
            echo "config.json file has been modified."
          else
            echo "Error: config.json file is not updated."
            exit 1
          fi

      - name: Check if version in config.json has been updated
        run: |
          VERSION_CHANGE=$(git diff HEAD^ HEAD firmware/config.json | grep 'version')
          if [ -n "$VERSION_CHANGE" ]; then
            echo "version in config.json has been updated."
          else
            echo "Error: version in config.json is not updated."
            exit 1
          fi
